print('Введите имя:')
name = input()
print('Введите фамилию:')
surname = input()
print('Введите любимое животное:')
favorite_animal = input()
print('Введите знак зодиака:')
zodiac_sign = input()
print('Индивидуальный гороскоп для пользователя', name, surname)
print('Кем вы были в прошлой жизни:', favorite_animal)
print('Ваш знак зодиака - ', zodiac_sign, ', поэтому вы - тонко чувствующая натура.')